on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Laravel translation checker action
        id: translations
        uses: larswiegers/laravel-translations-checker-action@v1
        with:
          directory: 'test'
      - name: Get the output time
        run: echo "The time was ${{ steps.translations.outputs.results }}"
